version: '2'
services:
  vault:
    ports:
    - 8200:8200/tcp
    labels:
      io.rancher.container.pull_image: always
    image: vault
    command: "vault server -config=/vault/config/local.json -log-level=info"
    environment:
      VAULT_LOCAL_CONFIG: ${config_data}
      VAULT_ADDR: http://127.0.0.1:8200
    stdin_open: true
    tty: true
    cap_add:
    - IPC_LOCK
