name: NHS Digital - Monitoring Services
description: |
  Stands up monitoring related clients and servers to enable metrics collection and display
version: 0.1
category: NHS-Digital
maintainer: NHS-Digital