name: NHS Digital - Vault
description: |
  Creates a Vault stack and single instance
version: 0.1
category: NHS-Digital
maintainer: NHS-Digital # The maintainer of the catalog entry
license: "N/A" # The license
projectURL: "N/A" # A URL related to the catalog entry
