version: '2'
services:
  verify-proxy:
    image: ${registry_url}/verify-proxy-cid:${vp_image_version}
    environment:
      DOMAIN: ${domain}
      SUB_DOMAIN: ${sub_domain}
    stdin_open: true
    tty: true
    ports:
    - 8082:9000/tcp
    labels:
      io.rancher.container.pull_image: always
  verify-service-provider:
    image: ${registry_url}/verify-service-provider-cid:${vsp_image_version}
    environment:
      hubMetadataURL: "https://compliance-tool-reference.ida.digital.cabinet-office.gov.uk/SAML2/metadata/federation"
      hubSSOLocation: "https://compliance-tool-reference.ida.digital.cabinet-office.gov.uk/SAML2/SSO"
      logLevel: "INFO"
      msaEntityId: "http://www.nhs-cid.gov.uk/SAML2/MD"
      msaMetadataURL: "http://matching-service-adapter.matching-service.rancher.internal:8080/matching-service/SAML2/metadata"
      port: "50400"
      samlPrimaryEncryptionKey: "${service_provider_vsp_primary_encryption_key}"
      samlSecondaryEncryptionKey: ""
      samlSigningKey: "${service_provider_vsp_primary_signing_key}"
      serviceEntityId: "http://www.nhs-cid.gov.uk/verify-service-provider"
    stdin_open: true
    tty: true
    ports:
    - 50400:50400/tcp
    labels:
      io.rancher.container.pull_image: always
