version: '2'
services:
  verify-proxy:
    image: ${registry_url}/verify-proxy-cid:${vp_image_version}
    environment:
      CLIENT_ID: ${vp_client_id}
      CLIENT_SECRET: ${vp_client_secret}
      DOMAIN: ${domain}
      REDIRECT_URI_0: "${vp_redirect_url_0}"
      REDIRECT_URI_1: "${vp_redirect_url_1}"
      REDIRECT_URI_2: "${vp_redirect_url_2}"
      SUB_DOMAIN: ${sub_domain}
      VSP_URL: "http://verify-service-provider.service-provider.rancher.internal:50400"
    stdin_open: true
    tty: true
    ports:
    - 8082:9000/tcp
    labels:
      io.rancher.container.pull_image: always
  verify-service-provider:
    image: ${registry_url}/verify-service-provider-cid:${vsp_image_version}
    environment:
      AWS_ACCOUNT_ID: ${aws_account_id}
      AWS_REGION: ${aws_region}
      ENV_SHORTCODE: "${env_shortcode}"
      HUB_METADATA_URL: "${vsp_hub_metadata_url}"
      HUB_SSO_LOCATION: "${vsp_hub_sso_location}"
      MSA_ENTITY_ID: "${vsp_msa_entity_id}"
      MSA_METADATA_URL: "${vsp_msa_metadata_url}"
      SERVICE_ENTITY_ID: "https://vp.${sub_domain}${domain}/verify-proxy/"
      VSP_SIGNING_KEY: "${vsp_primary_signing_key}"
      VSP_ENCRYPTION_KEY: "${vsp_primary_encryption_key}"
    stdin_open: true
    tty: true
    ports:
    - 50400:50400/tcp
    labels:
      io.rancher.container.pull_image: always
