.catalog:
  name: "NHS Digital - CID - Keycloak Stack"
  version: "0.1"
  description: "NHS Digital - CID - Keycloak Stack"
  minimum_rancher_version: "v1.1.4"
  questions:
    - variable: "registry_url"
      description: "Please enter your Registry"
      label: "Registry URL"
      required: true
      type: "string"
      default: "242530456444.dkr.ecr.eu-west-2.amazonaws.com"
    - variable: "image_version"
      description: "Please enter your chosen image version"
      label: "Image Version"
      required: true
      type: "string"
      default: "latest"
    - variable: "postgres_host"
      description: "Please enter your RDS Host FQDN/IP"
      label: "KeyCloak Postgres host"
      required: true
      type: "string"
      default: "localhost"
    - variable: "postgres_port"
      description: "Please enter your KeyCloak Postgres Port"
      label: "KeyCloak Postgres Port"
      required: true
      type: "string"
      default: "5432"
    - variable: "postgres_user"
      description: "Please enter your KeyCloak Postgres User"
      label: "KeyCloak Postgres Username"
      required: true
      type: "string"
      default: "keycloak"
    - variable: "postgres_password"
      description: "Please enter your KeyCloak Postgres Password"
      label: "KeyCloak Postgres Password"
      required: true
      type: "string"
      default: "password"

verify-proxy:
  scale: 1
  start_on_create: true
verify-service-provider:
  scale: 1
  start_on_create: true
