.catalog:
  name: "NHS Digital - CID - Keycloak Stack"
  version: "0.1"
  description: "NHS Digital - CID - Keycloak Stack"
  minimum_rancher_version: "v1.1.4"
  questions:
    - variable: "registry_url"
      description: "Please enter your Registry"
      label: "Registry URL"
      required: true
      type: "string"
      default: "242530456444.dkr.ecr.eu-west-2.amazonaws.com"
    - variable: "vp_image_version"
      description: "Please enter your chosen VP image version"
      label: "Image Version"
      required: true
      type: "string"
      default: "latest"
    - variable: "vsp_image_version"
      description: "Please enter your chosen VSP image version"
      label: "Image Version"
      required: true
      type: "string"
      default: "latest"

verify-proxy:
  scale: 1
  start_on_create: true
verify-service-provider:
  scale: 1
  start_on_create: true
