.catalog:
  name: "NHS Digital - CID - Keycloak Stack"
  version: "0.1"
  description: "NHS Digital - CID - Keycloak Stack"
  minimum_rancher_version: "v1.1.4"
  questions:
    - variable: "registry_url"
      description: "Please enter your Registry"
      label: "Registry URL"
      required: true
      type: "string"
      default: "242530456444.dkr.ecr.eu-west-2.amazonaws.com"
    - variable: "vp_image_version"
      description: "Please enter your chosen VP image version"
      label: "Image Version"
      required: true
      type: "string"
      default: "latest"
    - variable: "vsp_image_version"
      description: "Please enter your chosen VSP image version"
      label: "Image Version"
      required: true
      type: "string"
      default: "latest"

verify-proxy:
  scale: 1
  start_on_create: true
  health_check:
    port: 9000
    interval: 5000
    unhealthy_threshold: 3
    request_line: 'GET "/verify-proxy/health" "HTTP/1.1\r\nHost: www"'
    healthy_threshold: 1
    response_timeout: 2000
    initializing_timeout: 10000
    reinitializing_timeout: 10000
    strategy: recreate
verify-service-provider:
  scale: 1
  start_on_create: true
  health_check:
    port: 50400
    interval: 5000
    unhealthy_threshold: 3
    request_line: 'GET "/admin/ping" "HTTP/1.1\r\nHost: www"'
    healthy_threshold: 1
    response_timeout: 2000
    initializing_timeout: 10000
    reinitializing_timeout: 10000
    strategy: recreate
