version: '2'
services:
  matching-service-proxy:
    image: ${registry_url}/verify-msa-proxy-cid:latest
    ports:
    - 443:443/tcp
    - 444:444/tcp
    labels:
      io.rancher.container.pull_image: always
    environment:
      AWS_ACCOUNT_ID: ${aws_account_id}
      AWS_REGION: ${aws_region}
      ENV_SHORTCODE: "${env_shortcode}"
  matching-service-adapter:
    image: ${registry_url}/verify-msa-cid:${msa_image_version}
    stdin_open: true
    tty: true
    # ports:
    # - 8080:8080/tcp
    # - 8081:8081/tcp
    labels:
      io.rancher.container.pull_image: always
    environment:
      AWS_ACCOUNT_ID: ${aws_account_id}
      AWS_REGION: ${aws_region}
      ENV_SHORTCODE: "int"
      HUB_TRUSTSTORE_FILE_PATH: ${msa_hub_truststore_file_path}
      HUB_TRUSTSTORE_PASSWORD: ${msa_hub_truststore_password}
      LMS_ACCOUNT_CREATION_URL: ${msa_lms_account_creation_url}
      LMS_MATCH_URL: ${msa_lms_match_url}
      METADATA_TRUSTSTORE_FILE_PATH: ${msa_metadata_truststore_file_path}
      METADATA_TRUSTSTORE_PASSWORD: ${msa_metadata_truststore_password}
      MSA_ENTITY_ID: ${msa_entity_id}
      MSA_EXTERNAL_URL: ${msa_external_url}
      MSA_SIGNING_CERT: ${msa_signing_cert}
      MSA_SIGNING_KEY: ${msa_signing_key}
      MSA_ENCRYPTION_CERT: ${msa_encryption_cert}
      MSA_ENCRYPTION_KEY: ${msa_encryption_key}
      VERIFY_FEDERATION_METADATA_URL: ${msa_verify_federation_metadata_url}
      VERIFY_SAML_SSO_URL: ${msa_verify_saml_sso_url}
  local-matching-service:
    image: ${registry_url}/local-matching-service-cid:${lms_image_version}
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
