.catalog:
  name: "NHS Digital - CID - Matching Service Stack"
  version: "0.1"
  description: "NHS Digital - CID - Matching Service Stack"
  minimum_rancher_version: "v1.1.4"
  questions:
    - variable: "registry_url"
      description: "Please enter your Registry"
      label: "Registry URL"
      required: true
      type: "string"
      default: "242530456444.dkr.ecr.eu-west-2.amazonaws.com"
    - variable: "msa_image_version"
      description: "Please enter your chosen MSA image version"
      label: "Image Version"
      required: true
      type: "string"
      default: "latest"
    - variable: "lms_image_version"
      description: "Please enter your chosen LMS image version"
      label: "Image Version"
      required: true
      type: "string"
      default: "latest"

matching-service-proxy:
  scale: 1
  start_on_create: true
matching-service-adapter:
  scale: 1
  start_on_create: true
  health_check:
    port: 8081
    interval: 5000
    unhealthy_threshold: 3
    request_line: 'GET "/healthcheck" "HTTP/1.1\r\nHost: www"'
    healthy_threshold: 1
    response_timeout: 2000
    initializing_timeout: 10000
    reinitializing_timeout: 10000
    strategy: recreate
local-matching-service:
  scale: 1
  start_on_create: true
  health_check:
    port: 50130
    interval: 5000
    unhealthy_threshold: 3
    request_line: 'POST "/local-matching/match" "HTTP/1.1\r\nHost: www"'
    healthy_threshold: 1
    response_timeout: 2000
    initializing_timeout: 10000
    reinitializing_timeout: 10000
    strategy: recreate
