version: '2'
services:
  emailrest:
    image: ${registry_url}/cid/emailrestinterface:${image_version}
    stdin_open: true
    tty: true
    ports:
    - 10010:10010/tcp
    labels:
      io.rancher.container.pull_image: always
    environment:
      EMAIL_LOGIN: "False"
      EMAIL_USE_TLS: "False"
      MESSAGE_WORKER_EMAIL_GATEWAY_URI: ${email_gateway}
      SMS_RECIPIENT_EMAIL_SUFFIX: ${email_suffix}
      WORKER_EMAIL_ADDRESS: ${email_address}
      WORKER_EMAIL_PASSWORD: ${email_password}
  mailcatcher:
    image: tophfr/mailcatcher
    stdin_open: true
    tty: true
    ports:
    - 1080:80/tcp
    labels:
      io.rancher.container.pull_image: always
