.catalog:
  name: "NHS Digital - CID - Keycloak Stack"
  version: "1.0"
  description: "NHS Digital - CID - Keycloak Stack"
  minimum_rancher_version: "v1.1.4"
  questions:
    - variable: "registry_url"
      description: "Please enter your Registry"
      label: "Registry URL"
      required: true
      type: "string"
      default: "242530456444.dkr.ecr.eu-west-2.amazonaws.com"
    - variable: "image_version"
      description: "Please enter your chosen image version"
      label: "Image Version"
      required: true
      type: "string"
      default: "latest"

emailrest:
  scale: 1
  start_on_create: true
mailcatcher:
  scale: 1
  start_on_create: true
