version: '2'
services:
  mailcatcher:
    image: tophfr/mailcatcher
    stdin_open: true
    tty: true
    ports:
    - 1080:80/tcp
    - 1025:25/tcp
    labels:
      io.rancher.container.pull_image: always
  Keycloak:
    image: xxx
    environment:
      POSTGRES_HOST: xxx
      POSTGRES_PORT: '123'
      POSTGRES_USERNAME: xxx
      POSTGRES_PASSWORD: xxx
    stdin_open: true
    tty: true
    ports:
    - 80:8080/tcp
    labels:
      io.rancher.container.pull_image: always
