.catalog:
  name: "NHS Digital - CID - Keycloak Stack"
  version: "1.0"
  description: "NHS Digital - CID - Keycloak Stack"
  minimum_rancher_version: "v1.1.4"
  questions:


mailcatcher:
  scale: 1
  start_on_create: true
Keycloak:
  scale: 1
  start_on_create: true
